"""Test suite for mojo-url.

Combines hand-written behavioral tests with a fixture-driven byte-match
harness: `test/data/fixtures.txt` is generated by `gen_fixtures.py` from
CPython's `urllib.parse`, and `test_fixtures_bytematch` asserts every one
of mojo-url's outputs equals Python's byte-for-byte.
`test_urljoin_rfc3986_table` checks the canonical RFC 3986 Section 5.4
reference-resolution table independently and prints the pass count.
"""

from std.testing import assert_equal, assert_true, TestSuite

from url import (
    urlparse,
    urlunparse,
    quote,
    quote_plus,
    unquote,
    unquote_plus,
    urlencode,
    parse_qs,
    parse_qsl,
    urljoin,
    ParseResult,
    QueryPair,
)


# ---------------------------------------------------------------------------
# Fixture plumbing
# ---------------------------------------------------------------------------


def _fields(line: String) -> List[String]:
    var out = List[String]()
    for part in line.split("\t"):
        out.append(String(part))
    return out^


def _split_on(s: String, sep: String) -> List[String]:
    var out = List[String]()
    for part in s.split(sep):
        out.append(String(part))
    return out^


def _pack_parse_result(r: ParseResult) -> String:
    var port_str = String()
    if r.port() >= 0:
        port_str = String(r.port())
    return (
        r.scheme + "|" + r.netloc + "|" + r.path + "|" + r.params + "|"
        + r.query + "|" + r.fragment + "|" + r.username() + "|"
        + r.password() + "|" + r.hostname() + "|" + port_str
    )


# ---------------------------------------------------------------------------
# Behavioral tests (hand-written)
# ---------------------------------------------------------------------------


def test_urlparse_full() raises:
    var r = urlparse(String("http://www.example.com/path;params?query=1#frag"))
    assert_equal(r.scheme, "http")
    assert_equal(r.netloc, "www.example.com")
    assert_equal(r.path, "/path")
    assert_equal(r.params, "params")
    assert_equal(r.query, "query=1")
    assert_equal(r.fragment, "frag")


def test_urlparse_userinfo_and_port() raises:
    var r = urlparse(String("https://user:pass@host.example.com:8080/a/b?c=d#e"))
    assert_equal(r.username(), "user")
    assert_equal(r.password(), "pass")
    assert_equal(r.hostname(), "host.example.com")
    assert_equal(r.port(), 8080)


def test_urlparse_ipv6() raises:
    var r = urlparse(String("http://[::1]:8080/path"))
    assert_equal(r.netloc, "[::1]:8080")
    assert_equal(r.hostname(), "::1")
    assert_equal(r.port(), 8080)


def test_urlparse_ipv6_no_port() raises:
    var r = urlparse(String("http://[2001:db8::1]/"))
    assert_equal(r.hostname(), "2001:db8::1")
    assert_equal(r.port(), -1)


def test_urlparse_ipv6_zone() raises:
    var r = urlparse(String("http://[fe80::1%25eth0]:80/"))
    assert_equal(r.hostname(), "fe80::1%25eth0")
    assert_equal(r.port(), 80)


def test_urlparse_scheme_lowercased() raises:
    var r = urlparse(String("HTTP://Example.COM/Path"))
    assert_equal(r.scheme, "http")
    assert_equal(r.netloc, "Example.COM")
    assert_equal(r.hostname(), "example.com")


def test_urlparse_relative() raises:
    var r = urlparse(String("path/only"))
    assert_equal(r.scheme, "")
    assert_equal(r.netloc, "")
    assert_equal(r.path, "path/only")


def test_urlparse_empty() raises:
    var r = urlparse(String(""))
    assert_equal(r.scheme, "")
    assert_equal(r.path, "")


def test_urlparse_opaque() raises:
    var r = urlparse(String("mailto:user@example.com"))
    assert_equal(r.scheme, "mailto")
    assert_equal(r.netloc, "")
    assert_equal(r.path, "user@example.com")


def test_urlparse_fragment_only() raises:
    var r = urlparse(String("#fragonly"))
    assert_equal(r.fragment, "fragonly")
    assert_equal(r.path, "")


def test_urlparse_no_scheme_leading_digit() raises:
    # '1abc:x' — scheme must start with an alpha, so no scheme is split.
    var r = urlparse(String("1abc:x"))
    assert_equal(r.scheme, "")
    assert_equal(r.path, "1abc:x")


def test_urlunparse_roundtrip() raises:
    var url = String("https://user:pass@host:8080/a/b?c=d#e")
    assert_equal(urlunparse(urlparse(url)), url)


def test_urlunparse_opaque() raises:
    var r = ParseResult(
        String("scheme"), String(""), String("opaque"),
        String(""), String(""), String(""),
    )
    assert_equal(urlunparse(r), "scheme:opaque")


def test_quote_basic() raises:
    assert_equal(quote(String("hello world")), "hello%20world")


def test_quote_unicode() raises:
    assert_equal(quote(String("café")), "caf%C3%A9")


def test_quote_safe_default_slash() raises:
    assert_equal(quote(String("a/b/c")), "a/b/c")


def test_quote_empty_safe() raises:
    assert_equal(quote(String("a/b/c"), String("")), "a%2Fb%2Fc")


def test_quote_custom_safe() raises:
    assert_equal(quote(String(":@x"), String(":@")), ":@x")


def test_quote_plus_space() raises:
    assert_equal(quote_plus(String("a b c")), "a+b+c")


def test_quote_plus_literal_plus() raises:
    assert_equal(quote_plus(String("a+b")), "a%2Bb")


def test_quote_plus_slash_encoded() raises:
    assert_equal(quote_plus(String("path/with/slash")), "path%2Fwith%2Fslash")


def test_unquote_basic() raises:
    assert_equal(unquote(String("hello%20world")), "hello world")


def test_unquote_unicode() raises:
    assert_equal(unquote(String("caf%C3%A9")), "café")


def test_unquote_invalid_utf8_replace() raises:
    # %C3 lead byte with non-continuation %28 → U+FFFD then '('.
    assert_equal(unquote(String("%C3%28")), "�(")


def test_unquote_incomplete_passthrough() raises:
    assert_equal(unquote(String("incomplete%2")), "incomplete%2")
    assert_equal(unquote(String("bad%zzhex")), "bad%zzhex")


def test_unquote_plus() raises:
    assert_equal(unquote_plus(String("a+b%20c")), "a b c")


def test_urlencode_basic() raises:
    var pairs: List[QueryPair] = [
        QueryPair(String("q"), String("hello world")),
        QueryPair(String("lang"), String("en")),
    ]
    assert_equal(urlencode(pairs), "q=hello+world&lang=en")


def test_urlencode_special() raises:
    var pairs: List[QueryPair] = [
        QueryPair(String("k"), String("a+b")),
        QueryPair(String("x"), String("c&d")),
    ]
    assert_equal(urlencode(pairs), "k=a%2Bb&x=c%26d")


def test_parse_qsl_repeated() raises:
    var pairs = parse_qsl(String("a=1&a=2&b=3"))
    assert_equal(len(pairs), 3)
    assert_equal(pairs[0].key, "a")
    assert_equal(pairs[0].value, "1")
    assert_equal(pairs[1].value, "2")
    assert_equal(pairs[2].key, "b")


def test_parse_qsl_blank_dropped() raises:
    var pairs = parse_qsl(String("flag&other=x"))
    assert_equal(len(pairs), 1)
    assert_equal(pairs[0].key, "other")


def test_parse_qsl_plus_decoded() raises:
    var pairs = parse_qsl(String("space=a+b+c"))
    assert_equal(pairs[0].value, "a b c")


def test_parse_qs_grouping() raises:
    var d = parse_qs(String("a=1&a=2&b=3"))
    assert_equal(len(d["a"]), 2)
    assert_equal(d["a"][0], "1")
    assert_equal(d["a"][1], "2")
    assert_equal(d["b"][0], "3")


def test_urljoin_absolute() raises:
    assert_equal(
        urljoin(String("http://a/b/c/d;p?q"), String("g")),
        "http://a/b/c/g",
    )


def test_urljoin_network_path() raises:
    assert_equal(
        urljoin(String("http://a/b/c/d;p?q"), String("//g")),
        "http://g",
    )


def test_urljoin_dotdot() raises:
    assert_equal(
        urljoin(String("http://a/b/c/d;p?q"), String("../../g")),
        "http://a/g",
    )


def test_urljoin_empty_ref() raises:
    assert_equal(
        urljoin(String("http://a/b/c/d;p?q"), String("")),
        "http://a/b/c/d;p?q",
    )


# ---------------------------------------------------------------------------
# RFC 3986 Section 5.4 conformance table (the headline number)
# ---------------------------------------------------------------------------


def _rfc_cases() -> List[QueryPair]:
    """The canonical RFC 3986 5.4 ref→expected pairs (base fixed below)."""
    return [
        # 5.4.1 Normal Examples
        QueryPair(String("g:h"), String("g:h")),
        QueryPair(String("g"), String("http://a/b/c/g")),
        QueryPair(String("./g"), String("http://a/b/c/g")),
        QueryPair(String("g/"), String("http://a/b/c/g/")),
        QueryPair(String("/g"), String("http://a/g")),
        QueryPair(String("//g"), String("http://g")),
        QueryPair(String("?y"), String("http://a/b/c/d;p?y")),
        QueryPair(String("g?y"), String("http://a/b/c/g?y")),
        QueryPair(String("#s"), String("http://a/b/c/d;p?q#s")),
        QueryPair(String("g#s"), String("http://a/b/c/g#s")),
        QueryPair(String("g?y#s"), String("http://a/b/c/g?y#s")),
        QueryPair(String(";x"), String("http://a/b/c/;x")),
        QueryPair(String("g;x"), String("http://a/b/c/g;x")),
        QueryPair(String("g;x?y#s"), String("http://a/b/c/g;x?y#s")),
        QueryPair(String(""), String("http://a/b/c/d;p?q")),
        QueryPair(String("."), String("http://a/b/c/")),
        QueryPair(String("./"), String("http://a/b/c/")),
        QueryPair(String(".."), String("http://a/b/")),
        QueryPair(String("../"), String("http://a/b/")),
        QueryPair(String("../g"), String("http://a/b/g")),
        QueryPair(String("../.."), String("http://a/")),
        QueryPair(String("../../"), String("http://a/")),
        QueryPair(String("../../g"), String("http://a/g")),
        # 5.4.2 Abnormal Examples
        QueryPair(String("../../../g"), String("http://a/g")),
        QueryPair(String("../../../../g"), String("http://a/g")),
        QueryPair(String("/./g"), String("http://a/g")),
        QueryPair(String("/../g"), String("http://a/g")),
        QueryPair(String("g."), String("http://a/b/c/g.")),
        QueryPair(String(".g"), String("http://a/b/c/.g")),
        QueryPair(String("g.."), String("http://a/b/c/g..")),
        QueryPair(String("..g"), String("http://a/b/c/..g")),
        QueryPair(String("./../g"), String("http://a/b/g")),
        QueryPair(String("./g/."), String("http://a/b/c/g/")),
        QueryPair(String("g/./h"), String("http://a/b/c/g/h")),
        QueryPair(String("g/../h"), String("http://a/b/c/h")),
        QueryPair(String("g;x=1/./y"), String("http://a/b/c/g;x=1/y")),
        QueryPair(String("g;x=1/../y"), String("http://a/b/c/y")),
        QueryPair(String("g?y/./x"), String("http://a/b/c/g?y/./x")),
        QueryPair(String("g?y/../x"), String("http://a/b/c/g?y/../x")),
        QueryPair(String("g#s/./x"), String("http://a/b/c/g#s/./x")),
        QueryPair(String("g#s/../x"), String("http://a/b/c/g#s/../x")),
    ]


def test_urljoin_rfc3986_table() raises:
    var base = String("http://a/b/c/d;p?q")
    var cases = _rfc_cases()
    var passed = 0
    for c in cases:
        var got = urljoin(base, c.key)
        if got == c.value:
            passed += 1
        else:
            print("  RFC MISMATCH ref=", c.key, " exp=", c.value, " got=", got)
    print("urljoin RFC-3986 5.4 table:", passed, "/", len(cases))
    assert_equal(passed, len(cases))


# ---------------------------------------------------------------------------
# Full fixture byte-match against CPython urllib.parse
# ---------------------------------------------------------------------------


def test_fixtures_bytematch() raises:
    var content = open(String("test/data/fixtures.txt"), "r").read()
    var total = 0
    var matched = 0
    for line_slice in content.split("\n"):
        var line = String(line_slice)
        if line.byte_length() == 0:
            continue
        var f = _fields(line)
        var kind = f[0]
        total += 1
        var got: String
        var expected: String

        if kind == "urlparse":
            got = _pack_parse_result(urlparse(f[1]))
            expected = f[2]
        elif kind == "urlunparse":
            var p = _split_on(f[1], "|")
            var r = ParseResult(
                p[0].copy(), p[1].copy(), p[2].copy(),
                p[3].copy(), p[4].copy(), p[5].copy(),
            )
            got = urlunparse(r)
            expected = f[2]
        elif kind == "quote":
            got = quote(f[2], f[1])
            expected = f[3]
        elif kind == "quote_plus":
            got = quote_plus(f[1])
            expected = f[2]
        elif kind == "unquote":
            got = unquote(f[1])
            expected = f[2]
        elif kind == "unquote_plus":
            got = unquote_plus(f[1])
            expected = f[2]
        elif kind == "urlencode":
            var pairs = List[QueryPair]()
            if f[1].byte_length() > 0:
                for seg in _split_on(f[1], ";"):
                    var eq = seg.find("=")
                    pairs.append(
                        QueryPair(
                            String(StringSlice(unsafe_from_utf8=seg.as_bytes()[0:eq])),
                            String(StringSlice(unsafe_from_utf8=seg.as_bytes()[eq + 1 :])),
                        )
                    )
            got = urlencode(pairs)
            expected = f[2]
        elif kind == "parse_qsl":
            var pairs = parse_qsl(f[1])
            var packed = String()
            for i in range(len(pairs)):
                if i > 0:
                    packed += "|"
                packed += pairs[i].key + "=" + pairs[i].value
            got = packed^
            # Expected packed value is field 2 (may be empty).
            expected = f[2] if len(f) > 2 else String()
        elif kind == "urljoin":
            got = urljoin(f[1], f[2])
            expected = f[3]
        else:
            raise Error("unknown fixture kind: " + kind)

        if got == expected:
            matched += 1
        else:
            print(
                "  FIXTURE MISMATCH [", kind, "] got=", got, " exp=", expected
            )

    print("Python-fixture byte-match:", matched, "/", total)
    assert_equal(matched, total)


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
